### ISSUE TITLE
How to make it work with webpack?

### ISSUE THREAD

**Issue by no-more** [data-uri/mimer#3]
Hello,

First of all thanks for your work.

I'm trying to bundle a project (which have an indirect dependency to `datauri` and `mimer`) with `webpack`.

But this generate the following error : 
```
 Error: ENOENT: no such file or directory, open '.\node_modules\mimer\lib/data/mime.types'
     at Object.fs.openSync (fs.js:646:18)
     at Object.fs.readFileSync (fs.js:551:33)
     at module.exports (webpack://node_modules/mimer/lib/data/parser.js?:9:8)
     at Object.eval (webpack://node_modules/mimer/lib/exec.js?:62:158)
     at eval (webpack://node_modules/mimer/lib/exec.js?:17:37)
     at Object.eval (webpack://node_modules/mimer/lib/exec.js?:20:2)
     at eval (webpack://node_modules/mimer/lib/exec.js?:68:30)
     at Object ./node_modules/mimer/lib/exec.js (/usr/src/app/main.bundle.js:6379:1)
     at __webpack_require__ (/usr/src/app/main.bundle.js:24:30)
     at eval (webpack://node_modules/mimer/mimer.js?:1:18)
```

Is there anyway to make this works with `webpack` (no access to filesystem at runtime).

Thanks a lot.

**Comment by inyono** [comment]
Similar problem here. I basically copied the corresponding file to the output directory (I'm compiling to Node so I don't have the runtime problem). I'm not too sure why the mime types have to be in its own file TBH.

**Comment by mbessieres** [comment]
Anyone find an elegant solution to this?

**Comment by no-more** [comment]
I ended up with a fork. It's not very clean but it works for me.

**Comment by martin-cech** [comment]
Hey, I just ran into this too. Could we get rid of mime.types file and use a JS file with require/import instead please? Since the file mime.types serves as a simple database, moving the data into JS file while keeping the same public API should be doable

**Comment by heldr** [comment]
Good news! `mime.types` file is no longer required in mimer 1.0 and datauri 2.0

See more in:

https://github.com/data-uri/mimer/releases/tag/v1.0.0
https://github.com/data-uri/datauri/releases/tag/v2.0.0
